version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672" # UI de administración de RabbitMQ
      - "5672:5672"   # Puerto de comunicación
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python producer.py
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - rabbitmq
